# Generated by Django 5.0.2 on 2024-03-05 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lh_app', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=55)),
                ('org_name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=55)),
                ('phone', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=55)),
                ('owner_name', models.CharField(max_length=55)),
                ('about_org', models.TextField(max_length=55)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
