# Generated by Django 5.0.2 on 2024-03-15 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lh_app', '0005_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=55)),
                ('activity_name', models.CharField(max_length=55)),
                ('charge', models.CharField(max_length=55)),
                ('duration', models.CharField(max_length=55)),
                ('contact', models.CharField(max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
