# Generated by Django 5.0.2 on 2024-04-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lh_app', '0007_organizers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organizers',
        ),
    ]
