# Generated by Django 5.0.2 on 2024-04-05 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lh_app', '0008_delete_organizers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('organizers_name', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('organizers_venue', models.CharField(default='Auditorium', max_length=55)),
                ('organizers_date', models.DateField(default=django.utils.timezone.now)),
                ('organizers_description', models.TextField()),
                ('organizers_pic', models.FileField(default='', upload_to='lh_app/event_images')),
            ],
        ),
    ]
