# Generated by Django 5.0.2 on 2024-04-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lh_app', '0009_organizers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organizers',
        ),
    ]
