# Generated by Django 5.0.2 on 2024-04-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lh_app', '0010_delete_organizers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=55)),
                ('receiver_id', models.CharField(max_length=55)),
                ('subject', models.CharField(max_length=55)),
                ('message', models.TextField(max_length=55)),
            ],
        ),
    ]
