# Generated by Django 5.0.2 on 2024-04-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lh_app', '0012_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_mode',
            field=models.CharField(max_length=50),
        ),
    ]
